"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var fs = require("fs");
var path = require("path");
var jsdom_1 = require("jsdom");
var fontDir = path.resolve(__dirname, '../.storybook/theme/fonts');
var files = fs.readdirSync(fontDir);
var svgFontFile = files.find(function (file) { return file.endsWith('.svg'); });
if (!svgFontFile) {
    throw new Error('No SVG font file found in fonts directory');
}
var svgFontPath = path.join(fontDir, svgFontFile);
var outputPath = path.resolve(__dirname, '../.storybook/icon-list.ts');
var svgContent = fs.readFileSync(svgFontPath, 'utf-8');
var dom = new jsdom_1.JSDOM(svgContent, { contentType: 'image/svg+xml' });
// @ts-ignore
var glyphs = Array.from(dom.window.document.querySelectorAll('glyph'));
// @ts-ignore
var iconNames = glyphs
    .map(function (g) { return g.getAttribute('glyph-name'); })
    .filter(function (name) { return Boolean(name); });
var tsContent = "// This file is generated by extract-icons.ts\n\nexport const PolarisIconList = ".concat(JSON.stringify(iconNames, null, 2), " as const;\n\nexport type PolarisIconName = typeof PolarisIconList[number];\n");
fs.writeFileSync(outputPath, tsContent, 'utf-8');
console.log("\u2705 Extracted ".concat(iconNames.length, " icons to ").concat(outputPath));
