import * as fs from 'fs';
import * as path from 'path';
import { JSDOM } from 'jsdom';

const fontDir = path.resolve(__dirname, '../.storybook/theme/fonts');
const files = fs.readdirSync(fontDir);
const svgFontFile = files.find(file => file.endsWith('.svg'));

if (!svgFontFile) {
  throw new Error('No SVG font file found in fonts directory');
}

const svgFontPath = path.join(fontDir, svgFontFile);
const outputPath = path.resolve(__dirname, '../.storybook/icon-list.ts');

const svgContent = fs.readFileSync(svgFontPath, 'utf-8');
const dom = new JSDOM(svgContent, { contentType: 'image/svg+xml' });

// @ts-ignore
const glyphs = Array.from(dom.window.document.querySelectorAll('glyph'));

// @ts-ignore
const iconNames = glyphs
  .map((g) => g.getAttribute('glyph-name'))
  .filter((name): name is string => Boolean(name));

const tsContent = `// This file is generated by extract-icons.ts

export const PolarisIconList = ${JSON.stringify(iconNames, null, 2)} as const;

export type PolarisIconName = typeof PolarisIconList[number];
`;

fs.writeFileSync(outputPath, tsContent, 'utf-8');
console.log(`✅ Extracted ${iconNames.length} icons to ${outputPath}`);
